all:
	./startup.sh

hash1:
	john hash1 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=raw-md5

hash2:
	john hash2 --wordlist=./dict --fork=2 --format=raw-md5

hash3:
	john hash3 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=bcrypt

hash4:
	john hash4 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=raw-sha256

hash5:
	john hash5 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=sha512crypt

hash6:
	john hash6 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=raw-md4

hash7:
	john hash7 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=bcrypt

hash8:
	john hash8 --single --fork=2 --format=raw-sha1

hash9:
	john hash9 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=raw-sha1

hash10:
	john hash10 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=descrypt

hash11:
	john hash11 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=bsdicrypt

hash12:
	john hash12 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2

hash13:
	john hash13 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=md5crypt

hash14:
	john hash14 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=sha256crypt

hash15:
	john hash15 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=sha512crypt

hash16:
	john hash16 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=bcrypt

hash17:
	john hash17 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=lm

hash18:
	john hash18 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=nt

hash19:
	john hash19 --wordlist=/usr/share/wordlists/rockyou.txt --fork=2 --format=xsha

hash20:
	john hash20 --wordlist=./dict --fork=2 --format=md5ns
